### ISSUE TITLE
Failed to load the python-autopep8 package

### ISSUE THREAD

**Issue by DannyChenQ** [markbaas/atom-python-autopep8#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [python-autopep8](https://github.com/markbaas/atom-python-autopep8) package 0.1.4

### Stack Trace

Failed to load the python-autopep8 package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.19.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-python-autopep8/lib/python-autopep8.coffee:1:5)
    at /packages/atom-python-autopep8/lib/python-autopep8.coffee:1:1)
    at /packages/atom-python-autopep8/lib/python-autopep8.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-python-autopep8/lib/index.coffee:1:18)
    at /packages/atom-python-autopep8/lib/index.coffee:1:1)
    at /packages/atom-python-autopep8/lib/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.19.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.19.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.19.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.19.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:887:35)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.19.0/resources/app/src/package.js:144:18)
```

### Commands

```
     -0:36.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
python-autopep8 0.1.4 
atom-python-package 0.7.1 
atom-python-run 0.8.1 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
atom-typescript 11.0.6 
autocomplete-python 1.10.0 
darkpython-syntax 0.5.0 
emmet 2.4.3 
file-icons 2.1.10 
highlight-selected 0.13.1 
Hydrogen 1.19.0 
hyperclick 0.1.3 
js-hyperclick 1.11.0 
linter 2.2.0 
linter-flake8 2.2.1 
linter-pylama 0.9.3 
linter-pylint 2.1.0 
linter-python 3.1.2 
linter-python-pep8 0.2.0 
monokai 0.24.0 
nom undefined 
npm undefined 
project-manager 3.3.5 
python-debugger 0.2.0 
python-indent 1.1.0 
python-tools 0.6.9 
quick-highlight 0.10.0 
Remote-FTP 1.1.3 
remote-sync 4.1.5 
script 3.15.0 
seti-ui 1.9.0 
simplified-chinese-menu 5.3.4 
tortoise-svn 0.5.1 
```

**Comment by hanryhu** [comment]
I received this error when I downloaded python-autopep8 package 0.1.4 from GitHub without also copying over the `node_modules`.  You could try going to your package folder `/packages/atom-python-autopep8/` and running `npm install`.

**Comment by rlrandolphIII** [comment]
python-autopep8 not running in Atom (windows)

I installed via conda (running Anaconda Python).
> conda install -c conda-forge autopep8

![image](https://user-images.githubusercontent.com/34195553/116801251-e5265400-aabc-11eb-9698-63b9da95ef5a.png)
